

export const FETCH_START = 'FETCH_START'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAIL = 'FETCH_FAIL'

export const FETCH_DETAIL_START = 'FETCH_DETAIL_START'
export const FETCH_DETAIL_SUCCESS = 'FETCH_DETAIL_SUCCESS'
export const FETCH_DETAIL_FAIL = 'FETCH_DETAIL_FAIL'

export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'


export const USER_LOGIN_START = 'USER_LOGIN_START'
export const USER_LOGIN_SUCESS = 'USER_LOGIN_SUCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'



export const USER_PROFILE_START = 'USER_PROFILE_START'
export const USER_PROFILE_SUCESS = 'USER_PROFILE_SUCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'


export const USER_PROFILE_UPDATE_START = 'USER_PROFILE_UPDATE_START'
export const USER_PROFILE_UPDATE_SUCESS = 'USER_PROFILE_UPDATE_SUCESS'
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL'
export const USER_UPDATE_REST = 'USER_UPDATE_REST'


export const CART_SAVE_SHAPPING_ADDRESS = 'CART_SAVE_SHAPPING_ADDRESS'


export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'


export const ORDER_CREATE_START = 'ORDER_CREATE_START'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'


export const ORDER_GET_START = 'ORDER_GET_START'
export const ORDER_GET_SUCCESS = 'ORDER_GET_SUCCESS'
export const ORDER_GET_FAIL = 'ORDER_GET_FAIL'
export const ORDER_GET_REST = 'ORDER_GET_REST'



export const ORDER_PAY_START = 'ORDER_PAY_START'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_REST = 'ORDER_PAY_REST'


export const ORDER_LIST_START = 'ORDER_LIST_START'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL' 
export const ORDER_LIST_REST = 'ORDER_LIST_REST' 



export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_SUCESS_REQUEST = 'USER_SUCESS_REQUEST'
export const USER_FAIL_REQUEST = 'USER_FAIL_REQUEST'
export const USER_LIST_REST = 'USER_LIST_REST'


export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'


export const USER_UPDATE_START = 'USER_UPDATE_START'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_ADMIN_REST = 'USER_UPDATE_ADMIN_REST' 




export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'


export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_REST = 'PRODUCT_CREATE_REST'


export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_REST = 'PRODUCT_UPDATE_REST'


export const ORDER_GET_ADMIN_START = 'ORDER_GET_ADMIN_START'
export const ORDER_GET_ADMIN_SUCCESS = 'ORDER_GET_ADMIN_SUCCESS'
export const ORDER_GET_ADMIN_FAIL = 'ORDER_GET_ADMIN_FAIL' 
export const ORDER_GET_ADMIN_REST = 'ORDER_GET_ADMIN_REST' 


export const ORDER_DELIEVER_START = 'ORDER_DELIEVER_START'
export const ORDER_DELIEVER_SUCCESS = 'ORDER_DELIEVER_SUCCESS'
export const ORDER_DELIEVER_FAIL = 'ORDER_DELIEVER_FAIL'
export const ORDER_DELIEVER_REST = 'ORDER_DELIEVER_REST' 



export const PRODUCT_UPDATE_REVIEW_REQUEST = 'PRODUCT_UPDATE_REVIEW_REQUEST'
export const PRODUCT_UPDATE_REVIEW_SUCCESS = 'PRODUCT_UPDATE_REVIEW_SUCCESS'
export const PRODUCT_UPDATE_REVIEW_FAIL = 'PRODUCT_UPDATE_REVIEW_FAIL'
export const PRODUCT_UPDATE_REVIEW_REST = 'PRODUCT_UPDATE_REST'



export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'