

export const FETCH_START = 'FETCH_START'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAIL = 'FETCH_FAIL'
export const FETCH_DETAIL_SUCCESS = 'FETCH_DETAIL_SUCCESS'

export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'


export const USER_LOGIN_START = 'USER_LOGIN_START'
export const USER_LOGIN_SUCESS = 'USER_LOGIN_SUCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'