

export const FETCH_START = 'FETCH_START'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAIL = 'FETCH_FAIL'
export const FETCH_DETAIL_SUCCESS = 'FETCH_DETAIL_SUCCESS'

export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'


export const USER_LOGIN_START = 'USER_LOGIN_START'
export const USER_LOGIN_SUCESS = 'USER_LOGIN_SUCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'



export const USER_PROFILE_START = 'USER_PROFILE_START'
export const USER_PROFILE_SUCESS = 'USER_PROFILE_SUCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'


export const USER_PROFILE_UPDATE_START = 'USER_PROFILE_UPDATE_START'
export const USER_PROFILE_UPDATE_SUCESS = 'USER_PROFILE_UPDATE_SUCESS'
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL'
export const USER_UPDATE_REST = 'USER_UPDATE_REST'


export const CART_SAVE_SHAPPING_ADDRESS = 'CART_SAVE_SHAPPING_ADDRESS'


export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'


export const ORDER_CREATE_START = 'ORDER_CREATE_START'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'


export const ORDER_GET_START = 'ORDER_GET_START'
export const ORDER_GET_SUCCESS = 'ORDER_GET_SUCCESS'
export const ORDER_GET_FAIL = 'ORDER_GET_FAIL'
export const ORDER_GET_REST = 'ORDER_GET_REST'



export const ORDER_PAY_START = 'ORDER_PAY_START'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_REST = 'ORDER_PAY_REST'


export const ORDER_LIST_START = 'ORDER_LIST_START'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL' 
export const ORDER_LIST_REST = 'ORDER_LIST_REST' 



export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_SUCESS_REQUEST = 'USER_SUCESS_REQUEST'
export const USER_FAIL_REQUEST = 'USER_FAIL_REQUEST'
export const USER_LIST_REST = 'USER_LIST_REST'